/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xqdd_view_DrawRectangle */

#ifndef _Included_com_xqdd_view_DrawRectangle
#define _Included_com_xqdd_view_DrawRectangle
#ifdef __cplusplus
extern "C" {
#endif
#undef com_xqdd_view_DrawRectangle_BASELINE_OFFSET_SAME_AS_HEIGHT
#define com_xqdd_view_DrawRectangle_BASELINE_OFFSET_SAME_AS_HEIGHT -InfD
#undef com_xqdd_view_DrawRectangle_EPSILON_ABSOLUTE
#define com_xqdd_view_DrawRectangle_EPSILON_ABSOLUTE 1.0E-5
#undef com_xqdd_view_DrawRectangle_DEFAULT_TRANSLATE_X
#define com_xqdd_view_DrawRectangle_DEFAULT_TRANSLATE_X 0.0
#undef com_xqdd_view_DrawRectangle_DEFAULT_TRANSLATE_Y
#define com_xqdd_view_DrawRectangle_DEFAULT_TRANSLATE_Y 0.0
#undef com_xqdd_view_DrawRectangle_DEFAULT_TRANSLATE_Z
#define com_xqdd_view_DrawRectangle_DEFAULT_TRANSLATE_Z 0.0
#undef com_xqdd_view_DrawRectangle_DEFAULT_SCALE_X
#define com_xqdd_view_DrawRectangle_DEFAULT_SCALE_X 1.0
#undef com_xqdd_view_DrawRectangle_DEFAULT_SCALE_Y
#define com_xqdd_view_DrawRectangle_DEFAULT_SCALE_Y 1.0
#undef com_xqdd_view_DrawRectangle_DEFAULT_SCALE_Z
#define com_xqdd_view_DrawRectangle_DEFAULT_SCALE_Z 1.0
#undef com_xqdd_view_DrawRectangle_DEFAULT_ROTATE
#define com_xqdd_view_DrawRectangle_DEFAULT_ROTATE 0.0
#undef com_xqdd_view_DrawRectangle_EFFECTIVE_ORIENTATION_LTR
#define com_xqdd_view_DrawRectangle_EFFECTIVE_ORIENTATION_LTR 0L
#undef com_xqdd_view_DrawRectangle_EFFECTIVE_ORIENTATION_RTL
#define com_xqdd_view_DrawRectangle_EFFECTIVE_ORIENTATION_RTL 1L
#undef com_xqdd_view_DrawRectangle_EFFECTIVE_ORIENTATION_MASK
#define com_xqdd_view_DrawRectangle_EFFECTIVE_ORIENTATION_MASK 1L
#undef com_xqdd_view_DrawRectangle_AUTOMATIC_ORIENTATION_LTR
#define com_xqdd_view_DrawRectangle_AUTOMATIC_ORIENTATION_LTR 0L
#undef com_xqdd_view_DrawRectangle_AUTOMATIC_ORIENTATION_RTL
#define com_xqdd_view_DrawRectangle_AUTOMATIC_ORIENTATION_RTL 2L
#undef com_xqdd_view_DrawRectangle_AUTOMATIC_ORIENTATION_MASK
#define com_xqdd_view_DrawRectangle_AUTOMATIC_ORIENTATION_MASK 2L
#undef com_xqdd_view_DrawRectangle_DEFAULT_CACHE
#define com_xqdd_view_DrawRectangle_DEFAULT_CACHE 0L
#undef com_xqdd_view_DrawRectangle_DEFAULT_DISABLE
#define com_xqdd_view_DrawRectangle_DEFAULT_DISABLE 0L
#undef com_xqdd_view_DrawRectangle_DEFAULT_MOUSE_TRANSPARENT
#define com_xqdd_view_DrawRectangle_DEFAULT_MOUSE_TRANSPARENT 0L
#undef com_xqdd_view_DrawRectangle_MIN_STROKE_WIDTH
#define com_xqdd_view_DrawRectangle_MIN_STROKE_WIDTH 0.0
#undef com_xqdd_view_DrawRectangle_MIN_STROKE_MITER_LIMIT
#define com_xqdd_view_DrawRectangle_MIN_STROKE_MITER_LIMIT 1.0
#undef com_xqdd_view_DrawRectangle_DEFAULT_STROKE_WIDTH
#define com_xqdd_view_DrawRectangle_DEFAULT_STROKE_WIDTH 1.0
#undef com_xqdd_view_DrawRectangle_DEFAULT_STROKE_MITER_LIMIT
#define com_xqdd_view_DrawRectangle_DEFAULT_STROKE_MITER_LIMIT 10.0
#undef com_xqdd_view_DrawRectangle_DEFAULT_STROKE_DASH_OFFSET
#define com_xqdd_view_DrawRectangle_DEFAULT_STROKE_DASH_OFFSET 0.0
#undef com_xqdd_view_DrawRectangle_NON_RECTILINEAR_TYPE_MASK
#define com_xqdd_view_DrawRectangle_NON_RECTILINEAR_TYPE_MASK -80L
/*
 * Class:     com_xqdd_view_DrawRectangle
 * Method:    test2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xqdd_view_DrawRectangle_test2
  (JNIEnv *, jobject);

/*
 * Class:     com_xqdd_view_DrawRectangle
 * Method:    foo
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_xqdd_view_DrawRectangle_foo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_xqdd_view_DrawRectangle_Border */

#ifndef _Included_com_xqdd_view_DrawRectangle_Border
#define _Included_com_xqdd_view_DrawRectangle_Border
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
