/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xqdd_view_MainView */

#ifndef _Included_com_xqdd_view_MainView
#define _Included_com_xqdd_view_MainView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xqdd_view_MainView
 * Method:    from_cpp1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xqdd_view_MainView_from_1cpp1
  (JNIEnv *, jobject);

/*
 * Class:     com_xqdd_view_MainView
 * Method:    from_cpp2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xqdd_view_MainView_from_1cpp2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_xqdd_view_MainView_Companion */

#ifndef _Included_com_xqdd_view_MainView_Companion
#define _Included_com_xqdd_view_MainView_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
